CREATE TABLE ENDERECO(
	ID				UNIQUEIDENTIFIER	NOT NULL,
	LOGRADOURO		VARCHAR(100)		NOT NULL,
	COMPLEMENTO		VARCHAR(50)			NOT NULL,
	NUMERO			VARCHAR(10)			NOT NULL,
	BAIRRO			VARCHAR(50)			NOT NULL,
	CIDADE			VARCHAR(100)		NOT NULL,
	ESTADO			VARCHAR(2)			NOT NULL,
	CEP				VARCHAR(10)			NOT NULL,
	CLIENTE_ID		UNIQUEIDENTIFIER	NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID));