--Script de criação da tabela de PRODUTO
CREATE TABLE PRODUTO(
	ID					UNIQUEIDENTIFIER	NOT NULL,
	NOME				VARCHAR(100)		NOT NULL,
	PRECO				DECIMAL(10,2)		NOT NULL,
	QUANTIDADE			INTEGER				NOT NULL,
	DATAHORACADASTRO	DATETIME			NOT NULL,
	PRIMARY KEY(ID));
