CREATE PROCEDURE SP_INSERIR_CLIENTE
	@NOME			VARCHAR(100),	--ENTRADA
	@CPF			VARCHAR(11),	--ENTRADA
	@LOGRADOURO		VARCHAR(100),	--ENTRADA
	@COMPLEMENTO	VARCHAR(50),	--ENTRADA
	@NUMERO			VARCHAR(10),	--ENTRADA
	@BAIRRO			VARCHAR(50),	--ENTRADA
	@CIDADE			VARCHAR(50),	--ENTRADA
	@ESTADO			VARCHAR(2),		--ENTRADA
	@CEP			VARCHAR(10)		--ENTRADA
AS
DECLARE
	@CLIENTE_ID		UNIQUEIDENTIFIER,
	@ENDERECO_ID	UNIQUEIDENTIFIER
BEGIN
	
	--GERANDO UM ID PARA O CLIENTE
	SET @CLIENTE_ID = NEWID();

	--GERANDO UM ID PARA O ENDERECO
	SET @ENDERECO_ID = NEWID();

	--ABRINDO UMA TRANSAÇÃO NO BANCO DE DADOS
	BEGIN TRANSACTION;

	--GRAVANDO OS DADOS DO CLIENTE
	INSERT INTO CLIENTE(ID, NOME, CPF)
	VALUES(@CLIENTE_ID, @NOME, @CPF);

	--GRAVANDO OS DADOS DO ENDEREÇO
	INSERT INTO ENDERECO(ID, LOGRADOURO, COMPLEMENTO, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, CLIENTE_ID)
	VALUES(@ENDERECO_ID, @LOGRADOURO, @COMPLEMENTO, @NUMERO, @BAIRRO, @CIDADE, @ESTADO, @CEP, @CLIENTE_ID);

	--FINALIZANDO A TRANSAÇÃO
	COMMIT;

END;
GO