CREATE PROCEDURE SP_AlterarFuncionario
	@ID				UNIQUEIDENTIFIER,	--ENTRADA
	@NOME			VARCHAR(100),		--ENTRADA
	@MATRICULA		VARCHAR(10),		--ENTRADA
	@CPF			VARCHAR(11)			--ENTRADA
AS
BEGIN

	--ABRINDO UMA TRANSAÇÃO NO BANCO DE DADOS
	BEGIN TRANSACTION;

	--ATUALIZADO OS DADOS DO CLIENTE
	UPDATE	FUNCIONARIO
	SET		NOME		= @NOME,
			MATRICULA	= @MATRICULA,
			CPF			= @CPF
	WHERE	ID = @FUNCIONARIO_ID;

	--FINALIZANDO A TRANSAÇÃO
	COMMIT;

END;
GO