--SCRIPT PARA CRIAR A TABELA DE CATEGORIA
CREATE TABLE CATEGORIA(
	ID				UNIQUEIDENTIFIER	PRIMARY KEY,
	NOME			VARCHAR(50)			NOT NULL UNIQUE);

GO

--SCRIPT PARA CADASTRAR CATEGORIAS
INSERT INTO CATEGORIA(ID, NOME) VALUES(NEWID(), 'INFORMÁTICA');
INSERT INTO CATEGORIA(ID, NOME) VALUES(NEWID(), 'ELETRÔNICOS');
INSERT INTO CATEGORIA(ID, NOME) VALUES(NEWID(), 'LIVRARIA');
INSERT INTO CATEGORIA(ID, NOME) VALUES(NEWID(), 'GAMES');
INSERT INTO CATEGORIA(ID, NOME) VALUES(NEWID(), 'OUTROS');
GO

--CONSULTAR AS CATEGORIAS
SELECT * FROM CATEGORIA;
GO