CREATE TABLE [dbo].[FUNCIONARIO]
(
	[ID]        UNIQUEIDENTIFIER    NOT NULL PRIMARY KEY,
    [NOME]      VARCHAR(150)        NOT NULL,
    [MATRICULA] VARCHAR(6)          NOT NULL UNIQUE,
    [CPF]       VARCHAR(11)         NOT NULL UNIQUE
)